# Generated by Django 5.1.6 on 2025-04-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmlog",
            name="finish_reason",
        ),
        migrations.RemoveField(
            model_name="llmlog",
            name="system_fingerprint",
        ),
    ]
