# Generated by Django 5.1.6 on 2025-04-06 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0004_alter_column_description"),
        ("llm", "0002_remove_llmlog_finish_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryExecutionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.TextField()),
                ("row_count", models.IntegerField()),
                ("elapsed_ms", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "database",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="ddp.database"),
                ),
                (
                    "llm_log",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="llm.llmlog"),
                ),
            ],
        ),
    ]
