# Generated by Django 5.1.6 on 2025-04-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0004_llmlog_agent"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="llmlog",
            table="llm_log",
        ),
    ]
