# Generated by Django 5.1.6 on 2025-04-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0005_alter_llmlog_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="queryexecutionlog",
            table="query_execution_log",
        ),
    ]
