# Generated by Django 5.1.6 on 2025-03-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("eng_name", models.CharField(db_comment="데이터베이스명", max_length=255)),
                ("kor_name", models.CharField(max_length=255)),
                ("description", models.TextField(db_comment="데이터베이스 설명")),
                (
                    "connection_info",
                    models.TextField(blank=True, db_comment="데이터베이스 접속 정보 JSON 문자열", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("schema_name", models.CharField(max_length=255)),
                ("eng_name", models.CharField(max_length=255)),
                ("kor_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("database", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddp.database")),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("eng_name", models.CharField(max_length=255)),
                ("kor_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("data_type", models.CharField(max_length=50)),
                ("column_seq", models.IntegerField(default=-1)),
                ("default_value", models.CharField(blank=True, max_length=255, null=True)),
                ("is_unique", models.BooleanField(default=False)),
                ("is_nullable", models.BooleanField(default=False)),
                ("is_primary_key", models.BooleanField(default=False)),
                ("is_foreign_key", models.BooleanField(default=False)),
                ("foreign_key_column", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "foreign_key_table",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ddp.column"
                    ),
                ),
                ("table", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddp.table")),
            ],
        ),
    ]
