# Generated by Django 5.1.6 on 2025-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="foreign_key_table",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
