# Generated by Django 5.1.6 on 2025-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0002_alter_column_foreign_key_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="data_type",
            field=models.TextField(),
        ),
    ]
