# Generated by Django 5.1.6 on 2025-04-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0003_alter_column_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
