# Generated by Django 5.1.6 on 2025-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0004_alter_column_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="init_step",
            field=models.IntegerField(db_comment="데이터베이스 초기 등록 단계", default=1),
        ),
    ]
