# Generated by Django 5.1.6 on 2025-04-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0005_database_init_step"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="database",
            name="init_step",
        ),
    ]
