# Generated by Django 5.1.6 on 2025-04-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0006_remove_database_init_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="db_type",
            field=models.CharField(blank=True, db_comment="DB 종류", max_length=255, null=True),
        ),
    ]
