# Generated by Django 5.1.6 on 2025-04-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0007_database_db_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="kor_name",
        ),
    ]
