# Generated by Django 5.1.6 on 2025-04-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0008_remove_table_kor_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="database",
            old_name="kor_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="database",
            name="eng_name",
        ),
    ]
