# Generated by Django 5.1.6 on 2025-04-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0009_rename_kor_name_database_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="column",
            name="kor_name",
        ),
    ]
