# Generated by Django 5.1.6 on 2025-04-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddp", "0010_remove_column_kor_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="column",
            old_name="eng_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="table",
            old_name="eng_name",
            new_name="name",
        ),
    ]
